apiVersion: v1
kind: Service
metadata:
  name: {{ template "{{.Chart.Name}}.name" . }}-self-monitoring
  annotations:
{{ include "{{.Chart.Name}}.prodInfoAnnotations" . | indent 4 }}
{{- if .Values.prometheus.monitoring }}
{{ toYaml .Values.prometheus.monitoring | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    chart: {{ template "{{.Chart.Name}}.chart" . }}
    app.kubernetes.io/name: {{ template "{{.Chart.Name}}.name" . }}
    app.kubernetes.io/version: {{ template "{{.Chart.Name}}.version" . }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    app: {{ template "{{.Chart.Name}}.name" . }}
    component: core
    env: {{ .Values.global.env | quote }}
spec:
{{- if .Values.services.dns.clusterIP }}
  clusterIP: {{ .Values.services.dns.clusterIP }}
{{- end }}
  ports:
{{- if .Values.config.prometheusMonitoring.enabled }}
    - name: metrics
      port: 3004
      targetPort: 3004
      protocol: TCP
{{- end }}
  selector:
    app: {{ template "{{.Chart.Name}}.name" . }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    component: core
